# Start Trusty Distribution
dist: trusty

# Speed-up processes by setting sudo to false
sudo: false

# Disable clone logs
git:
  quiet: true

# Generic language for Terraform and Terragrunt
language: generic

# Install Terraform and Terragrunt
before_script:
- curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.11.8/terraform_0.11.8_linux_amd64.zip
- curl -sLo /tmp/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v0.17.0/terragrunt_linux_amd64
- unzip /tmp/terraform.zip -d /tmp
- mv /tmp/terraform ~/bin
- mv /tmp/terragrunt ~/bin
- chmod +x /tmp/terraform
- chmod +x /tmp/terragrunt
- export PATH="~/bin:$PATH"

jobs:
  include:
  - stage: "Plan Changes"
    script:
    - bash scripts/plan.sh
#  - stage: "Apply Changes"
#    script:
#    - bash scripts/apply.sh
#  - stage: "Destroy Changes"
#    script:
#    - bash scripts/destroy.sh
